# Generated by Django 3.0.2 on 2020-03-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sportField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldId', models.CharField(max_length=20)),
                ('fieldName', models.CharField(max_length=100)),
                ('fieldLocation', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sportField',
            },
        ),
    ]
