# Generated by Django 3.0.2 on 2020-03-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportFields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportfield',
            name='fieldId',
            field=models.CharField(max_length=100),
        ),
    ]
