# Generated by Django 3.0.2 on 2020-03-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportFields', '0002_auto_20200311_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportfield',
            name='fieldId',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='sportfield',
            table=None,
        ),
    ]
