# Generated by Django 3.0.2 on 2020-03-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportFields', '0003_auto_20200311_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportfield',
            name='fieldId',
            field=models.IntegerField(),
        ),
    ]
